[default.extend-identifiers]
raisons = "raisons"
Mosquitto = "Mosquitto"
Espace = "Mosquitto"
# google verification key in <Header />
8qVBtr6GGGesE5nlacfO8rAmqBL9giPwr4FIouqVYO4 = "8qVBtr6GGGesE5nlacfO8rAmqBL9giPwr4FIouqVYO4"

# golb-articles - software.md
snd_hda_intel = "snd_hda_intel"
DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING = "DANGEROUS_ENABLE_DEVTOOLS_ONLY_ENABLE_IF_YOU_KNOW_WHAT_YOURE_DOING"
"ba" = "ba"


[files]
extend-exclude = [
    "src/styles/markdown.css",
    "Its-Just-Nans/data/projects/projects.json",
    "Its-Just-Nans/data/pull_requests/pulls.json",
    "Its-Just-Nans/others-articles/certifications/*",
    "Its-Just-Nans/others-articles/assets/*",
    "Its-Just-Nans/others-articles/cool-quotes/*",
    "Its-Just-Nans/others-articles/gta-chinatown-wars/gta-chinatown-wars.mdx",
    "Its-Just-Nans/others-articles/tocs/tocs.mdx",
    "Its-Just-Nans/others-articles/telecom-paris/telecom-paris.mdx",
]
